export const sourcesRender: Record<string, string> = {
  "header": `vec2 p=(FC.xy*2.-r)/r.y,x,d;for(float i=1.-fract(t);i<25.;i+=.5)x=p+(cos(i*vec2(.8,.5)+t)+vec2(0,4.-i))/i,d=vec2(4,sin(i)*.4)/i,o+=(cos(i+vec4(0,2,4,0))+1.)/(length(x-d*clamp(dot(x,d)/dot(d,d),-1.,1.))+i/1e3)/max(i*i,5.)*.1;`,
  "explition-two": `float i,j,d=.1,D,e;vec3 p;for(i=0.;i++<64.&&d>1e-4;){p=vec3((FC.xy-.5*r)/r.y,e);p=vec3(log(D=length(p.xy)*2.),p.y,atan(p.x,p.z));p.xy*=rotate2D(t*.5);for(j=0.;j++<5.;)p=abs(abs(p)-.05)-.04,d=max(max(p.z,p.x),p.y),d-=D/2e4;e+=d;}o+=vec4(exp(p*p),1)*5./i;`,
  "explition-three": `for(float i,g,e,s;++i<60.;o.rgb+=hsv(.1,e*.4,s/2e3)){vec3 p=vec3((FC.xy-.5*r)/r.y*1.5*(cos(t*.5)*.5+1.5),g-.6);p.zy*=rotate2D(t*.5);s=1.;for(int i;i++<15;p=vec3(3,5,1)-abs(abs(p)*e-vec3(4,2,2)))s*=e=max(1.005,8./dot(p,p));g+=mod(length(p.zx),p.y)/s;s=log(s)/g;}`,
  "explition-four": `for(float i,g,e,s;++i<60.;o.rgb+=hsv(e-g,.6,s/8e3)){vec3 p=vec3((FC.xy-.5*r)/r.y*3.,g-.5)*rotate3D(t,vec3(2,2,sin(t)));;s=2.;for(int i;i++<9;p=vec3(3,6,1)-abs(abs(p)*e-vec3(4,1,2)))s*=e=max(1.05,6./dot(p,p));g+=mod(length(p.zx),p.y)/s;s=log(s)/g;}`,
  "explition-five": `float i,j,d=.1,e;vec3 p,q=vec3(-1,0,1.5);for(i=0.;i++<64.&&d>1e-4;){p=vec3((FC.xy-.5*r)/r.y,e);for(j=0.;j++<6.;)p=abs(p*rotate3D(t,q)*mix(q,p*p,1.64)),d=min(max(p.z,p.y),p.x),e-=d;}o+=vec4(exp(p-q),1)*3./i;`,
  "explition-one": `float i,j,d=.1,D,e;vec3 p;for(i=0.;i++<64.&&d>1e-4;){p=vec3((FC.xy-.5*r)/r.y,e)*2.;p=vec3(log(D=length(p)),exp(p.y*i),atan(p.x,p.z));p.yx*=rotate2D(-t);for(j=0.;j++<7.;)p=abs(abs(p)-.05)-.04,d=min(min(p.x,p.z),p.y),d-=D/1e4;e+=d;}o+=vec4(exp(p*vec3(-1)),1)*5./i;`,
  "loadingAnimationResult": `float i,j,d=.1,e,h;vec3 p,q=vec3(-1.5);for(i=0.;i++<64.&&d>1e-4;){p=vec3((FC.xy-.5*r)/r.y,e);p.z-=.5;p.xy-=.4;p*=rotate3D(t,q);for(j=0.;j++<2.;)p=abs(abs(p*mix(p,q,vec3(-.8)))-.05)-.05,h=clamp(dot(p,q)/dot(q,q),-1.,2.);d=length(p-q*h)-.005;e+=d;}o+=3./i;`,
  "vector": `vec2 p=(FC.xy*2.-r)/r.y,v;for(float i=.2,l;i<1.;o+=(cos(i*5.+vec4(0,1,2,3))+1.)*(1.+v.y/(l=length(v)+.003))/l/1e2)v=vec2(mod(atan(p.x,p.y)+i+i*t,PI2)-PI,1)*length(p)-i,v.x-=clamp(v.x+=i,-i,i),i+=.05;o=tanh(o);`
  // "vector": `vec2 p=(FC.xy*2.-r)/r.y,v;for(float i=.2,l;i<1.;o+=(cos(i*5.+vec4(0,1,2,3))+1.)*(1.+v.y/(l=length(v)+.003))/l/1e2)v=vec2(mod(atan(p.y,p.x)+i+i*t,PI2)-PI,1)*length(p)-i,v.x-=clamp(v.x+=i,-i,i),i+=.05;o=tanh(o);`
}
